# wiki-js + NFS volumes docker compose file ready to deploy in docker swarm as a stack
---
version: "3.8"
services:
  pgsql_db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wikijs
      POSTGRES_PASSWORD: wikijs
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    volumes:
      - "db-data:/var/lib/postgresql/data"
  cron:
    image: postgres:11-alpine
    command: crond -f -l 8
    volumes:
      - "backups:/mnt/backups"
      - "crontab:/etc/periodic/weekly/:ro"
    depends_on:
      - pgsql_db
  wiki:
    image: requarks/wiki:2
    depends_on:
      - pgsql_db
    environment:
      DB_TYPE: postgres
      DB_HOST: pgsql_db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijs
      DB_NAME: wikijs
    ports:
      - "80:3000"
    volumes:
      - "wiki-js:/config"
      - "wiki-js:/data"
volumes:
  db-data:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=10.6.131.60,rw
      device: ":/storage/docker/wiki-js/volumes/db-data"
  backups:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=10.6.131.60,rw
      device: ":/storage/backups/wikijs"
  crontab:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=10.6.131.60,rw
      device: ":/storage/docker/wiki-js/volumes/crontab"
  wiki-js:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=10.6.131.60,rw
      device: ":/storage/docker/wiki-js/volumes/wiki-js"
